apiVersion: v1
kind: PersistentVolume
metadata:
  name: static_file_share_pv
spec:
  capacity:
    storage: 5Gi
  accessMode:
    - ReadWriteMany
  azureFile: 
    secretName: azure-fs-secret
    shareName: aks_pod_file_share # name of the file share
    readOnly: false
  mountOptions:
  - dir_mode=0777
  - file_mdoe=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
  - actimeo=30
