apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure_file_share_pvc
spec:
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: "" # Leaving the storage class name as blank means we are statically binding the PV
