# represents the volume that is on the node
# incase you are using docker the node will be docker deamon
# In this example we are creating the a socket volume on host that points to docker.sock

apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-with-volumes
  labels:
    app: nginx-hostpath-volumes
specs:
  volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
        type: Socket    
  containers:
  - name: nginx-app
    image: nginx:alpine
    command: ["sleep"]  # command to run on docker / docker commands
    args: ["10000"]
    volumeMounts:
    - name: docker-socket
      mountPath: /var/run/docker.sock
