apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels: # Labels are often used to connect two or more resources
    app: nginx-app
spec:
  containers:
  -  name: nginx-container
     image: nginx:alpine
     ports:
     - containerPort: 80  # Container port