apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-with-health-probe
  labels:
    app: nginx-pod-with-liveness-probe
spec:
  containers:
  -  name: nginx-probe-container-httpgetaction
     image: nginx:alpine
     ports:
       - containerPort: 80
     readinessProbe:
       httpGet:
         path: /index.html
         port: 80
       initialDelaySeconds: 2
       periodSeconds: 5