apiVersion: v1
kind: Service
metadata:
  name: node-port-service
  labels:
    scope: frontEnd
spec:
  type: NodePort  # can be nodePort, LoadBAlancer
  selector:
    app: nginx-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31000 # This is optional, if this is not defined the service will automatically assign a port
