apiVersion: v1
kind: Service
metadata:
  name: cluster-ip-service
  labels:
    app: nginx
    scope: frontEnd
spec:
  selector:
    app: nginx-app   # Label that matches with the pod
  ports:
  - name: http
    port: 80  # port at which service will be running
    targetPort: 80 # Port to which the service whould redirect the request to