apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    scope: frontEnd
spec:
  type: LoadBalancer  # can be nodePort, LoadBAlancer
  selector:
    app: nginx-app
  ports:
  - port: 8080    # port user can point to / access
    targetPort: 80